### PR TITLE
exercise 6

### PR DESCRIPTION
**Pull request by aniekanokpokpo**

### CODE REVIEW

**Comment by Jonesey13** [comment]
Designated Reviewer: Alex

**Review by Jonesey13 — CHANGES_REQUESTED** [review]
This is nearly there but there is one major issue that needs addressing:

1. Your dotted boxes aren't consistent between diagrams. For example Trello is outside the dotted box in the container diagram but is absent from the context diagram. Similarly the TODO Web App is outside the dotted box in the component diagram but is absent from the container diagram.

**Comment by aniekanokpokpo** [comment]
> This is nearly there but there is one major issue that needs addressing:
> 
> 1. Your dotted boxes aren't consistent between diagrams. For example Trello is outside the dotted box in the container diagram but is absent from the context diagram. Similarly the TODO Web App is outside the dotted box in the component diagram but is absent from the container diagram.

updated. please review again :)

**Review by JackMeadDev — CHANGES_REQUESTED** [review]
Thanks for updating your context diagram, but unfortunately it looks like you committed the wrong file for your component diagram however as it is a duplicate of your container diagram!

**Comment by aniekanokpokpo** [comment]
> Thanks for updating your context diagram, but unfortunately it looks like you committed the wrong file for your component diagram however as it is a duplicate of your container diagram!

updated the diagrams

**Review by hugh-emerson — APPROVED** [review]
The component diagram could be improved a bit further:

- The box outside the dotted line should be labelled either web server or user, not "TODO Web App" - that's what the dotted box itself should be labelled.
- You could break it down a bit more. E.g separate components for "templates" and "route controller". 

But it's generally good and I'm happy for you to merge this.

**Comment by aniekanokpokpo** [comment]
> The component diagram could be improved a bit further:
> 
> * The box outside the dotted line should be labelled either web server or user, not "TODO Web App" - that's what the dotted box itself should be labelled.
> * You could break it down a bit more. E.g separate components for "templates" and "route controller".
> 
> But it's generally good and I'm happy for you to merge this.

Updated the component diagram

**Pull request merged**
